# Generated by Django 5.0.2 on 2024-03-05 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImgModel',
            fields=[
                ('carimg_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_img', models.ImageField(upload_to='')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.carmodel')),
            ],
            options={
                'db_table': 'CarImage',
            },
        ),
    ]
