# Generated by Django 5.0.2 on 2024-03-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_carimgmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='persons',
            field=models.IntegerField(null=True),
        ),
    ]
