# Generated by Django 5.0.2 on 2024-03-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_carmodel_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='car_fuel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
