# Generated by Django 5.0.2 on 2024-03-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_carmodel_car_fuel_carmodel_car_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_model',
            new_name='car_company',
        ),
        migrations.AlterField(
            model_name='carimgmodel',
            name='car_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
