# Generated by Django 5.0.2 on 2024-03-31 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_rename_car_model_carmodel_car_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='PlacesModel',
            fields=[
                ('places_id', models.AutoField(primary_key=True, serialize=False)),
                ('places', models.CharField(max_length=200)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.locationmodel')),
            ],
            options={
                'db_table': 'Places',
            },
        ),
    ]
