# Generated by Django 5.0.2 on 2024-04-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_locationmodel_placesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmodel',
            old_name='admin_pasw',
            new_name='admin_password',
        ),
    ]
