# Generated by Django 5.0.2 on 2024-04-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_rename_admin_pasw_adminmodel_admin_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='car_year',
        ),
    ]
