# Generated by Django 5.0.2 on 2024-04-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_remove_carmodel_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=100, null=True),
        ),
    ]
