# Generated by Django 5.0.2 on 2024-04-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0009_alter_carmodel_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_fuel',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=100, null=True),
        ),
    ]
