# Generated by Django 5.0.2 on 2024-04-04 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_alter_carmodel_car_fuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInteriorsModel',
            fields=[
                ('car_interior_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_interior', models.ImageField(upload_to='car_interiors/')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.carmodel')),
            ],
            options={
                'db_table': 'Car_Interior_Images',
            },
        ),
    ]
