# Generated by Django 5.0.2 on 2024-03-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='licenseimgmodel',
            table='User_License',
        ),
        migrations.AlterModelTable(
            name='userprofilepic',
            table='Profile_Pic',
        ),
    ]
