# Generated by Django 5.0.2 on 2024-03-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_licenseimgmodel_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
