# Generated by Django 5.0.2 on 2024-03-29 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0005_rename_car_model_carmodel_car_company_and_more'),
        ('UserApp', '0003_userregmodel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup', models.CharField(max_length=200)),
                ('pickup_date', models.DateField()),
                ('dropof', models.CharField(max_length=200)),
                ('dropof_date', models.DateField()),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.carmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.userregmodel')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
