# Generated by Django 5.0.2 on 2024-04-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_commentmodel_booking_commentmodel_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='booking',
        ),
    ]
