# Generated by Django 5.0.2 on 2024-04-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_remove_commentmodel_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='action',
            field=models.BooleanField(default=False),
        ),
    ]
