# Generated by Django 5.0.2 on 2024-04-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_paymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
