# Generated by Django 5.0.2 on 2024-05-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_paymentmodel_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='razorpay_payment_signature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
